### ISSUE TITLE
Reusable components

### ISSUE THREAD

**Issue by siddharthd0** [TechOptimum/techoptimum.org#40]
Make these rows reusable components so it is more efficient.

<img width="1440" alt="Screen Shot 2023-04-09 at 10 27 17 AM" src="https://user-images.githubusercontent.com/96356209/230784551-84b621af-2b65-4f37-9701-0cdc71e65bbc.png">

**Comment by richard1615** [comment]
Can this issue be assigned to me?

**Comment by siddharthd0** [comment]
Assigned @richard1615
