### ISSUE TITLE
Center certain text

### ISSUE THREAD

**Issue by siddharthd0** [TechOptimum/techoptimum.org#42]
Center `EIN: 88-3677650 | team@techoptimum.org` when on mobile

<img width="1440" alt="Screen Shot 2023-04-09 at 10 33 36 AM" src="https://user-images.githubusercontent.com/96356209/230784868-5a084426-f272-48f8-8dcf-676a7213a844.png">

**Comment by crystalchavez99** [comment]
Currently working on this, wanted to check out with approval on this based on these screenshots of different mobile view in regards to centering the text.
![image](https://user-images.githubusercontent.com/88100670/232099121-3e71257d-6b92-4aa0-94f7-fc71035fa61b.png)
![image](https://user-images.githubusercontent.com/88100670/232099193-363d26e0-99b4-4421-a2c0-4d040698d96d.png)

**Comment by siddharthd0** [comment]
Looks good
